# Generated by Django 6.0.2 on 2026-02-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0002_comment_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='media',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
